# Generated by Django 5.1.6 on 2025-02-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_privacypolicy_privacypolicyparagraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
