# Generated by Django 5.1.6 on 2025-02-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_companyinfo_email_companyinfo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram'),
        ),
    ]
