# Generated by Django 5.1.6 on 2025-02-28 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_companyinfo_telegram_link'),
        ('containers', '0013_container_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=50, verbose_name='Название')),
                ('full_title', models.CharField(max_length=255, verbose_name='Полное название')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.brand', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Раздел документации',
            },
        ),
    ]
