# Generated by Django 5.1.6 on 2025-02-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_documentationsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationsection',
            options={'verbose_name': 'раздел документации', 'verbose_name_plural': 'Документация'},
        ),
        migrations.CreateModel(
            name='DocumentationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('doc_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.documentationsection', verbose_name='Раздел документации')),
            ],
            options={
                'verbose_name': 'файл документации',
                'verbose_name_plural': 'файлы документации',
            },
        ),
    ]
