# Generated by Django 5.1.6 on 2025-02-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_documentationsection_options_documentationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationfile',
            name='file',
            field=models.FileField(upload_to='documentation/', verbose_name='Файл'),
        ),
    ]
