# Generated by Django 5.1.6 on 2025-02-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_documentationfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentationsection',
            old_name='full_title',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='documentationsection',
            old_name='short_title',
            new_name='short_name',
        ),
    ]
