# Generated by Django 5.1.6 on 2025-02-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_rename_full_title_documentationsection_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationfile',
            name='doc_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contacts.documentationsection', verbose_name='Раздел документации'),
        ),
    ]
