# Generated by Django 5.1.6 on 2025-03-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_popularquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('company_member', models.CharField(blank=True, max_length=100, null=True, verbose_name='Представитель компании')),
                ('company_member_image', models.ImageField(blank=True, null=True, upload_to='contacts/partners/members/', verbose_name='Фото представителя компании')),
                ('logo', models.FileField(upload_to='contacts/partners/logo/', verbose_name='Логотип')),
                ('quote', models.CharField(blank=True, max_length=150, null=True, verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
