# Generated by Django 5.1.6 on 2025-03-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='delivery_info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Доставка (текст)'),
        ),
    ]
