# Generated by Django 5.1.6 on 2025-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_companyinfo_delivery_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='delivery_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Доставка (текст)'),
        ),
    ]
