# Generated by Django 5.1.6 on 2025-03-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_companyinfo_delivery_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='payment_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Оплата (текст)'),
        ),
    ]
