# Generated by Django 5.1.6 on 2025-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_companyinfo_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='warranty_info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Гарантия (текст)'),
        ),
    ]
