# Generated by Django 5.1.6 on 2025-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_companyinfo_warranty_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='warranty_info',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='warranty_info_for_new',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Гарантия для новых контейнеов (текст)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='warranty_info_for_used',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Гарантия для б/у контейнеов (текст)'),
        ),
    ]
