# Generated by Django 5.1.6 on 2025-03-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_cityinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='email',
        ),
    ]
