# Generated by Django 5.1.6 on 2025-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_remove_companyinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='requisites_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Реквизиты'),
        ),
    ]
