# Generated by Django 5.1.6 on 2025-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_companyinfo_requisites_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_full_name',
            field=models.CharField(blank=True, default='ООО "Техно Транс"', max_length=100, null=True, verbose_name='Полное наименование компании'),
        ),
    ]
