# Generated by Django 5.1.6 on 2025-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_companyinfo_company_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites_file',
            field=models.FileField(blank=True, null=True, upload_to='documentation/requisites/', verbose_name='Реквизиты'),
        ),
    ]
