# Generated by Django 5.1.6 on 2025-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_alter_companyinfo_requisites_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfo',
            name='full_address',
            field=models.CharField(default='', max_length=150, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
