# Generated by Django 5.1.6 on 2025-03-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_cityinfo_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfo',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
