# Generated by Django 5.1.6 on 2025-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_cityinfo_whatsapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinfo',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на Telegram'),
        ),
    ]
