# Generated by Django 5.1.6 on 2025-02-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='slug',
            field=models.SlugField(default='', max_length=500, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
