# Generated by Django 5.1.6 on 2025-02-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_container_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
