# Generated by Django 5.1.6 on 2025-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_container_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='category',
        ),
        migrations.AddField(
            model_name='container',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_containers', to='containers.category', verbose_name='Категория'),
        ),
    ]
