# Generated by Django 5.1.6 on 2025-02-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_remove_container_category_container_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='categories',
            field=models.ManyToManyField(related_name='category_containers', to='containers.category', verbose_name='Категория'),
        ),
    ]
