# Generated by Django 5.1.6 on 2025-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_alter_container_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='description',
            field=models.TextField(default='', max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='container',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_containers', to='containers.category', verbose_name='Категория'),
        ),
    ]
