# Generated by Django 5.1.6 on 2025-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0008_container_description_alter_container_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Описание'),
        ),
    ]
