# Generated by Django 5.1.6 on 2025-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0009_alter_container_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='Описание'),
        ),
    ]
