# Generated by Django 5.1.6 on 2025-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_alter_container_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='height_inner',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Высота внутренняя'),
        ),
        migrations.AddField(
            model_name='container',
            name='height_outer',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Высота внешняя'),
        ),
        migrations.AddField(
            model_name='container',
            name='length_inner',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина внутренняя'),
        ),
        migrations.AddField(
            model_name='container',
            name='length_outer',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длина внешняя'),
        ),
        migrations.AddField(
            model_name='container',
            name='max_load',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Максимальная загрузка'),
        ),
        migrations.AddField(
            model_name='container',
            name='max_weight_gross',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Макс. масса брутто'),
        ),
        migrations.AddField(
            model_name='container',
            name='tare_weight',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Вес тары'),
        ),
        migrations.AddField(
            model_name='container',
            name='width_inner',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ширина внутренняя'),
        ),
        migrations.AddField(
            model_name='container',
            name='width_outer',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ширина внешняя'),
        ),
    ]
