# Generated by Django 5.1.6 on 2025-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0011_container_height_inner_container_height_outer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='door_width',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ширина дверного проёма'),
        ),
        migrations.AddField(
            model_name='container',
            name='doorh_height',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Высота дверного проёма'),
        ),
    ]
