# Generated by Django 5.1.6 on 2025-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0012_container_door_width_container_doorh_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='old_price',
            field=models.IntegerField(default=0, verbose_name='Старая цена'),
        ),
    ]
