# Generated by Django 5.1.6 on 2025-03-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0013_container_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='containers.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_containers', to='containers.containertype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='container',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_containers', to='containers.containermodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='container',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
