# Generated by Django 5.1.6 on 2025-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0014_alter_container_brand_alter_container_container_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='year',
            field=models.SmallIntegerField(default=-1, verbose_name='Год выпуска'),
        ),
    ]
