# Generated by Django 5.1.6 on 2025-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0015_alter_container_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
