# Generated by Django 5.1.6 on 2025-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0016_alter_container_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
    ]
