# Generated by Django 5.1.6 on 2025-03-10 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0017_alter_container_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Загрузите видео контейнера', upload_to='containers/videos/', verbose_name='Видео')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='containers.container', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
