# Generated by Django 5.1.6 on 2025-03-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0018_containervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='with_nds',
            field=models.BooleanField(default=True, verbose_name='Цены указаны с НДС'),
        ),
    ]
