# Generated by Django 5.1.6 on 2025-03-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0020_category_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='specs',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Характеристики (текст)'),
        ),
    ]
