# Generated by Django 5.1.6 on 2025-03-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0021_container_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Компрессор',
                'verbose_name_plural': 'Компрессоры',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='compressor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.compressor', verbose_name='Компрессор'),
        ),
    ]
