# Generated by Django 5.1.6 on 2025-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0022_compressor_container_compressor'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объём, м. куб. не более'),
        ),
    ]
