# Generated by Django 5.1.6 on 2025-03-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0023_container_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='specs',
        ),
    ]
