# Generated by Django 5.1.6 on 2025-03-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0024_remove_container_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizationCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город локализации',
                'verbose_name_plural': 'Города локализации',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='localization_city',
            field=models.ManyToManyField(to='containers.localizationcity', verbose_name='Город локализации'),
        ),
    ]
