# Generated by Django 5.1.6 on 2025-03-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0025_localizationcity_container_localization_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='localization_city',
            new_name='localization_cities',
        ),
    ]
