# Generated by Django 5.1.6 on 2025-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0026_rename_localization_city_container_localization_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='localization_cities',
            field=models.ManyToManyField(blank=True, null=True, to='containers.localizationcity', verbose_name='Город локализации'),
        ),
    ]
