# Generated by Django 5.1.6 on 2025-04-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0027_alter_container_localization_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Рефконтейнер', 'verbose_name_plural': 'Рефконтейнеры'},
        ),
        migrations.AlterField(
            model_name='containerimage',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='containers.container', verbose_name='Рефконтейнер'),
        ),
        migrations.AlterField(
            model_name='containervideo',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='containers.container', verbose_name='Рефконтейнер'),
        ),
    ]
