# Generated by Django 5.1.6 on 2025-04-11 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0028_alter_container_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.SmallIntegerField(default=-1, verbose_name='Год выпуска')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('slug', models.SlugField(max_length=500, verbose_name='Слаг')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Описание')),
                ('with_nds', models.BooleanField(default=True, verbose_name='Цены указаны с НДС')),
                ('length_outer', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина внешняя')),
                ('width_outer', models.SmallIntegerField(blank=True, null=True, verbose_name='Ширина внешняя')),
                ('height_outer', models.SmallIntegerField(blank=True, null=True, verbose_name='Высота внешняя')),
                ('length_inner', models.SmallIntegerField(blank=True, null=True, verbose_name='Длина внутренняя')),
                ('width_inner', models.SmallIntegerField(blank=True, null=True, verbose_name='Ширина внутренняя')),
                ('height_inner', models.SmallIntegerField(blank=True, null=True, verbose_name='Высота внутренняя')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Объём, м. куб. не более')),
                ('max_weight_gross', models.SmallIntegerField(blank=True, null=True, verbose_name='Макс. масса брутто')),
                ('tare_weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Вес тары')),
                ('max_load', models.SmallIntegerField(blank=True, null=True, verbose_name='Максимальная загрузка')),
                ('door_width', models.SmallIntegerField(blank=True, null=True, verbose_name='Ширина дверного проёма')),
                ('doorh_height', models.SmallIntegerField(blank=True, null=True, verbose_name='Высота дверного проёма')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='containers.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='universal_category_containers', to='containers.category', verbose_name='Категория')),
                ('compressor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.compressor', verbose_name='Компрессор')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universal_type_containers', to='containers.containertype', verbose_name='Тип')),
                ('localization_cities', models.ManyToManyField(blank=True, null=True, to='containers.localizationcity', verbose_name='Город локализации')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universal_model_containers', to='containers.containermodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Контейнер',
                'verbose_name_plural': 'Контейнеры',
            },
        ),
        migrations.CreateModel(
            name='ContainerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Загрузите видео контейнера', upload_to='containers/videos/', verbose_name='Видео')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universal_videos', to='universal_containers.universalcontainer', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='UniversalContainerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='containers/', verbose_name='Картинка')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universal_images', to='universal_containers.universalcontainer', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
