# Generated by Django 5.1.6 on 2025-04-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_containers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContainerVideo',
            new_name='UniversalContainerVideo',
        ),
    ]
