# Generated by Django 5.1.6 on 2025-02-17 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Мощность дизель-генератора',
                'verbose_name_plural': 'Мощности дизель-генераторов',
            },
        ),
        migrations.CreateModel(
            name='GeneratorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип дизель-генератора',
                'verbose_name_plural': 'Типы дизель-генераторов',
            },
        ),
        migrations.CreateModel(
            name='RepairPartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория дизель-генераторов',
                'verbose_name_plural': 'Категории дизель-генераторов',
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.SmallIntegerField(verbose_name='Год выпуска')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('slug', models.SlugField(max_length=500, verbose_name='Слаг')),
                ('old_price', models.IntegerField(default=0, verbose_name='Старая цена')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Описание')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_generators', to='generators.generatorpower', verbose_name='Мощность номинальная, квт')),
                ('generator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_generators', to='generators.generatortype', verbose_name='Тип')),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='category_generators', to='generators.repairpartcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Контейнер',
                'verbose_name_plural': 'Контейнеры',
            },
        ),
    ]
