# Generated by Django 5.1.6 on 2025-02-17 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0002_generatorcategory_delete_repairpartcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generators/', verbose_name='Картинка')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='generators.generator', verbose_name='Генератор')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
