# Generated by Django 5.1.6 on 2025-02-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0003_generatorimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatorcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='generatorpower',
            options={'verbose_name': 'Мощность', 'verbose_name_plural': 'Мощности'},
        ),
        migrations.AlterModelOptions(
            name='generatortype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
    ]
