# Generated by Django 5.1.6 on 2025-02-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0004_alter_generatorcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generator',
            options={'verbose_name': 'Дизель-генератор', 'verbose_name_plural': 'Дизель-генераторы'},
        ),
    ]
