# Generated by Django 5.1.6 on 2025-03-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0006_generator_with_nds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_generators', to='generators.generatorpower', verbose_name='Мощность номинальная, квт'),
        ),
    ]
