# Generated by Django 5.1.6 on 2025-03-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0007_alter_generator_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='generator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_generators', to='generators.generatortype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
    ]
