# Generated by Django 5.1.6 on 2025-03-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0008_alter_generator_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модель генератора',
                'verbose_name_plural': 'Модели генераторов',
            },
        ),
        migrations.AlterField(
            model_name='generator',
            name='generator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_generators', to='generators.generatortype', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='generator',
            name='generator_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generators.generatormodel', verbose_name='Модель'),
        ),
    ]
