# Generated by Django 5.1.6 on 2025-03-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0009_generatormodel_alter_generator_generator_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='generator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_generators', to='generators.generatortype', verbose_name='Тип'),
        ),
    ]
