# Generated by Django 5.1.6 on 2025-02-16 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0013_container_old_price'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, max_length=200, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.category', verbose_name='Тип контейнера')),
            ],
            options={
                'verbose_name': 'Заявка на расчёт стоимости',
                'verbose_name_plural': 'Заявки на расчёт стоимости',
            },
        ),
    ]
