# Generated by Django 5.1.6 on 2025-02-16 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatepricerequest',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.servicetype', verbose_name='Вид обслуживания'),
        ),
    ]
